version: "3"
services:
  postgres:
    image: "postgres"
    volumes:
    - ./volumes/postgresql-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=Password1!
    ports:
    - 5432:5432
