version: "3"
services:
  postgres:
    image: "postgres:10"
    volumes:
    - ./volumes/postgresql-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=Password1!
    ports:
    - 5432:5432
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbit"
    ports:
    - 5672:5672
    - 15672:15672
